language: java
install:
- bash install.sh
script:
- bash test.sh
before_script:
- bash pull.sh
after_success:
- bash push.sh
env:
  global:
    secure: CLj1bldTanwmKbdgJ+pz7v+AjkljCV1NxlY05xihtw5Adj5DcPEee5r3KcG33bZx/lY8U2i3uS/hUOCeCzoXVZMIPs28sF6H4/tIL3PXVr4WUZRM39Evf1+c9LnD9dpKboD5qAlP11C207goEZ+/Fuacuw1pJFX13l4u9CjibQOSZC1yRsMFgLvLky/oj2tWWNSIJxjY47skvc2O8SCf0Ibzbkypx2vB4duTl5cqhYOhDeW7t37WMxEjMtunFxDmbIbDe13kMvbUUTjZ8CLn0wiZvPDG9Bdxwa50Rh3cDYqLY4RoZuRiMLXkoAjJ75hibLQioED7CEtMdyaKzsCU7cfjcBoaYSHyihUs7uAabt86wuheRn80MGdpAwwLZVbS+hd2dx2DwjbQK3YlxBTdgflp/Kq57YDcwTsU3m5322VaMPc9dnuEfRH6QVi++OWwgXrD/B9knDyFGAmP3arZIeCEwSarfqzHxjnigZ126jfShIQA+2h5oR+tifZZmC1PQWDpoGD1CbqoIoIL34D3HqlvpnHDz3ZrlVN1lkO6gvC7KVC1yqtZklPLnfElOY4yufeAAjkMyEVaevkM2uZoJDwe9hNf4Ixo7IbDGiHK/CRGmZJmT4ZMV+XDDR7eNiVl2+PhF+qgV8qSI67PPdJm801q2ah8O0xQUr4h/dUI8Eo=
